# Generated by Django 6.0 on 2026-06-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='facility',
            field=models.CharField(choices=[('gym', 'Gym'), ('gym_ac', 'Fitness Gym (AC)'), ('gym_nonac', 'Fitness Gym (Non-AC)'), ('gym_monthly', 'Fitness Gym (Monthly)'), ('turf', 'Football Turf'), ('turf_weekday', 'Football Turf (Weekday)'), ('turf_weekend', 'Football Turf (Weekend)'), ('badminton_1', 'Badminton Court 1'), ('badminton_2', 'Badminton Court 2'), ('badminton_3', 'Badminton Court 3')], max_length=20),
        ),
    ]
