# Generated by Django 6.0 on 2026-06-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_booking_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hours',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
