# Generated by Django 6.0 on 2026-07-17 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_member_payment_slot_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(default='booking', max_length=20)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
    ]
