# Generated by Django 6.0 on 2026-07-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pricingsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='facility',
            field=models.CharField(choices=[('gym', 'Gym'), ('gym_ac', 'Fitness Gym (AC)'), ('gym_nonac', 'Fitness Gym (Non-AC)'), ('gym_monthly', 'Fitness Gym (Monthly)'), ('gym_ac_monthly', 'Fitness Gym (AC) - Monthly'), ('gym_ac_quarterly', 'Fitness Gym (AC) - Quarterly'), ('gym_ac_halfyearly', 'Fitness Gym (AC) - Half-Yearly'), ('gym_ac_yearly', 'Fitness Gym (AC) - Yearly'), ('gym_nonac_monthly', 'Fitness Gym (Non-AC) - Monthly'), ('gym_nonac_quarterly', 'Fitness Gym (Non-AC) - Quarterly'), ('gym_nonac_halfyearly', 'Fitness Gym (Non-AC) - Half-Yearly'), ('gym_nonac_yearly', 'Fitness Gym (Non-AC) - Yearly'), ('total_membership', 'Total Membership'), ('turf', 'Football Turf'), ('turf_weekday', 'Football Turf (Weekday)'), ('turf_weekend', 'Football Turf (Weekend)'), ('badminton_1', 'Badminton Court 1'), ('badminton_2', 'Badminton Court 2'), ('badminton_3', 'Badminton Court 3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('gym_ac', 'Gym AC'), ('gym_nonac', 'Gym Non-AC'), ('gym_monthly', 'Gym Monthly'), ('gym_ac_monthly', 'Gym AC - Monthly'), ('gym_ac_quarterly', 'Gym AC - Quarterly'), ('gym_ac_halfyearly', 'Gym AC - Half-Yearly'), ('gym_ac_yearly', 'Gym AC - Yearly'), ('gym_nonac_monthly', 'Gym Non-AC - Monthly'), ('gym_nonac_quarterly', 'Gym Non-AC - Quarterly'), ('gym_nonac_halfyearly', 'Gym Non-AC - Half-Yearly'), ('gym_nonac_yearly', 'Gym Non-AC - Yearly'), ('total_membership', 'Total Membership (All Access)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='slot',
            name='facility',
            field=models.CharField(choices=[('gym', 'Gym'), ('gym_ac', 'Fitness Gym (AC)'), ('gym_nonac', 'Fitness Gym (Non-AC)'), ('gym_monthly', 'Fitness Gym (Monthly)'), ('gym_ac_monthly', 'Fitness Gym (AC) - Monthly'), ('gym_ac_quarterly', 'Fitness Gym (AC) - Quarterly'), ('gym_ac_halfyearly', 'Fitness Gym (AC) - Half-Yearly'), ('gym_ac_yearly', 'Fitness Gym (AC) - Yearly'), ('gym_nonac_monthly', 'Fitness Gym (Non-AC) - Monthly'), ('gym_nonac_quarterly', 'Fitness Gym (Non-AC) - Quarterly'), ('gym_nonac_halfyearly', 'Fitness Gym (Non-AC) - Half-Yearly'), ('gym_nonac_yearly', 'Fitness Gym (Non-AC) - Yearly'), ('total_membership', 'Total Membership'), ('turf', 'Football Turf'), ('turf_weekday', 'Football Turf (Weekday)'), ('turf_weekend', 'Football Turf (Weekend)'), ('badminton_1', 'Badminton Court 1'), ('badminton_2', 'Badminton Court 2'), ('badminton_3', 'Badminton Court 3')], max_length=20),
        ),
    ]
